---
title: "Comparison of Pollen Traps"
subtitle: "Evaluation of Similarity and Robustness of Three Swisens Poleno-type Pollen Traps Located in Payerne During the Birch Blooming Season 2020"
author: "Simon Adamov"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
always_allow_html: TRUE
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      error = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.retina =2.5,
                      fig.width = 10,
                      fig.height = 6,
                      out.width = "100%",
                      out.height = "100%")
# This project is using renv dependency management, for more info: https://cran.r-project.org/web/packages/renv/vignettes/renv.html

library(caTools)
library(MASS)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(here)
library(lme4)
library(psych)
library(robustlmm)
library(goftest)
library(kableExtra)

# library(Amelia) # only used for one fct call to missmap()
# library(data.table) # only used for transpose()
# library(dunn.test)
# library(conover.test)

devtools::load_all()

# I like the look of these plots
# devtools::install_github('cttobin/ggthemr')
# library(ggthemr)
ggthemr("fresh")

# caTools and bitops are required to knit this vignette, those are not tracked by renv and must be installed by the user
# Due to old R-Version caTools must be installed from CRAN Archive, in order to knit markdown documents.
# packageurl <- "http://cran.r-project.org/src/contrib/Archive/caTools/caTools_1.17.1.1.tar.gz"
# install.packages(packageurl, repos=NULL, type="source")

```

```{r cache = TRUE}

path_data <- paste0(here::here(), "/ext-data/")
files_data <- list.files(path_data, pattern = "raw_data")

data_raw_poleno <-
  map(files_data, ~ data.table::fread(paste0(path_data, .x))) %>% 
  setNames(files_data)

names <- names(data_raw[[1]])
names[3] <- "timestamp1"
names[12] <- "timestamp2"
names[1] <- "id1"
names[10] <- "id2"
names[16] <- "contextVersionId2"

data_poleno <- map2(data_raw_poleno, 1:3, ~.x %>% 
  setNames(names) %>% 
  select(classLabel, timestamp) %>% 
  mutate(timestamp = as_datetime(timestamp),
         classLabel = as_factor(classLabel),
         date = date(timestamp),
         hour = hour(timestamp) + 1,
         trap = paste0("poleno", .y)) %>% 
  filter(timestamp > ymd_hms("2020-02-15 00:00:00"),
         timestamp <= ymd_hms("2020-05-03 23:59:59")))

# summary(data)
# glimpse(data)
# head(data, 200)

# Device_idDevice, deviceVersion, valid have the same values for all observations
# The three timestamps are merely seconds apart. For now I simply decided to use one of them. All of them are in agreement with the eventBaseName. 

```

```{r}

# Hour 1 represents the duration 00:00:01 - 01:00:00, and same for all hours up to 24
data_poleno_hourly <- map2(data_poleno, 1:3, ~.x %>% 
  group_by(date, hour, trap) %>% 
  summarise(total = as.integer(n())) %>% 
  ungroup() %>% 
  mutate(timestamp = ymd_hm(paste0(date, sprintf("%02d", hour), ":00"))) %>% 
  padr::pad(by = "timestamp") %>%  # This will populate missing hours with zeros where no pollen were measured (actually very few)
  mutate(total = if_else(is.na(total), 0L, total), # Padding introduced 119 NAs
         date = date(timestamp), 
         hour = hour(timestamp),
         trap = paste0("poleno", .y))) 

```

```{r}

# We should import the same data from the DWH. The CATs don't work on windows or in a renv session (very well), so I exported the data using climap and stored it in the ext-data folder. 
# We need Pollen Concentrations for Payerne (PPY) for all available species (the classifier for Poleno is not yet functional and produces non-sense labels).

files_hirst <- list.files(path_data, pattern = "dwh.csv")

data_hirst <- data.table::fread(paste0(path_data, files_hirst)) %>% 
  as_tibble() %>%
  select(- katacuh0) %>% # This seems to be a combination of two species already counted separately.
  mutate_at(vars(khambrh0:khjunch0), ~ if_else(. < 0, 0, .)) %>% 
  mutate(timestamp = dmy_hm(timestamp),
         date = date(timestamp),
         hour = hour(timestamp) + 1,
         trap = "hirst",
         total = rowSums(select(., -timestamp))) %>% 
  filter(timestamp >= ymd_hms("2020-02-15 00:00:00"),
         timestamp < ymd_hms("2020-05-04 00:00:00")) %>% 
  mutate(timestamp = timestamp + hours(1)) %>% # To align it with my definition of hour (mine go from 01-24, the original data from 0-23)
  select(timestamp, date, hour, trap, total)

```

```{r fig.height=10}


data_hourly_comb <- data_poleno_hourly %>% 
  bind_rows %>% 
  bind_rows(data_hirst) 

data_hourly_comb %>% 
  ggplot(aes(x = timestamp, y = total, col = trap)) +
  geom_line() +
  ggtitle("Hourly Total Pollen Counts") +
  labs(x = "Date")

data_hourly_comb %>% 
  # mutate() %>% 
  group_by(timestamp) %>%
  mutate_at(vars(total), function(x){
      if(all(as.integer(x) == 0))
        return(NA) # This will set all measurements to NA if no trap measured any pollen
      else
        return(x)
  }) %>% 
  summary
```








